/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as AboutRouteRouteImport } from './routes/about/route'
import { Route as landingRouteRouteImport } from './routes/(landing)/route'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as landingIndexRouteImport } from './routes/(landing)/index'
import { Route as AboutUserIdRouteImport } from './routes/about/$userId'
import { Route as AboutJoinUsRouteRouteImport } from './routes/about/join-us/route'
import { Route as DashboardItemsIndexRouteImport } from './routes/dashboard/items/index'
import { Route as AboutJoinUsIndexRouteImport } from './routes/about/join-us/index'
import { Route as landingContactUsIndexRouteImport } from './routes/(landing)/contact-us/index'
import { Route as DashboardItemsItemIdRouteImport } from './routes/dashboard/items/$itemId'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRouteRoute = AboutRouteRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const landingRouteRoute = landingRouteRouteImport.update({
  id: '/(landing)',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AboutRouteRoute,
} as any)
const landingIndexRoute = landingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => landingRouteRoute,
} as any)
const AboutUserIdRoute = AboutUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AboutRouteRoute,
} as any)
const AboutJoinUsRouteRoute = AboutJoinUsRouteRouteImport.update({
  id: '/join-us',
  path: '/join-us',
  getParentRoute: () => AboutRouteRoute,
} as any)
const DashboardItemsIndexRoute = DashboardItemsIndexRouteImport.update({
  id: '/items/',
  path: '/items/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AboutJoinUsIndexRoute = AboutJoinUsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AboutJoinUsRouteRoute,
} as any)
const landingContactUsIndexRoute = landingContactUsIndexRouteImport.update({
  id: '/contact-us/',
  path: '/contact-us/',
  getParentRoute: () => landingRouteRoute,
} as any)
const DashboardItemsItemIdRoute = DashboardItemsItemIdRouteImport.update({
  id: '/items/$itemId',
  path: '/items/$itemId',
  getParentRoute: () => DashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/about': typeof AboutRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/about/join-us': typeof AboutJoinUsRouteRouteWithChildren
  '/about/$userId': typeof AboutUserIdRoute
  '/': typeof landingIndexRoute
  '/about/': typeof AboutIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/login': typeof LoginIndexRoute
  '/dashboard/items/$itemId': typeof DashboardItemsItemIdRoute
  '/contact-us': typeof landingContactUsIndexRoute
  '/about/join-us/': typeof AboutJoinUsIndexRoute
  '/dashboard/items': typeof DashboardItemsIndexRoute
}
export interface FileRoutesByTo {
  '/about/$userId': typeof AboutUserIdRoute
  '/': typeof landingIndexRoute
  '/about': typeof AboutIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/login': typeof LoginIndexRoute
  '/dashboard/items/$itemId': typeof DashboardItemsItemIdRoute
  '/contact-us': typeof landingContactUsIndexRoute
  '/about/join-us': typeof AboutJoinUsIndexRoute
  '/dashboard/items': typeof DashboardItemsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(landing)': typeof landingRouteRouteWithChildren
  '/about': typeof AboutRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/about/join-us': typeof AboutJoinUsRouteRouteWithChildren
  '/about/$userId': typeof AboutUserIdRoute
  '/(landing)/': typeof landingIndexRoute
  '/about/': typeof AboutIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/login/': typeof LoginIndexRoute
  '/dashboard/items/$itemId': typeof DashboardItemsItemIdRoute
  '/(landing)/contact-us/': typeof landingContactUsIndexRoute
  '/about/join-us/': typeof AboutJoinUsIndexRoute
  '/dashboard/items/': typeof DashboardItemsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/about'
    | '/dashboard'
    | '/about/join-us'
    | '/about/$userId'
    | '/'
    | '/about/'
    | '/dashboard/'
    | '/login'
    | '/dashboard/items/$itemId'
    | '/contact-us'
    | '/about/join-us/'
    | '/dashboard/items'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about/$userId'
    | '/'
    | '/about'
    | '/dashboard'
    | '/login'
    | '/dashboard/items/$itemId'
    | '/contact-us'
    | '/about/join-us'
    | '/dashboard/items'
  id:
    | '__root__'
    | '/(landing)'
    | '/about'
    | '/dashboard'
    | '/about/join-us'
    | '/about/$userId'
    | '/(landing)/'
    | '/about/'
    | '/dashboard/'
    | '/login/'
    | '/dashboard/items/$itemId'
    | '/(landing)/contact-us/'
    | '/about/join-us/'
    | '/dashboard/items/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  landingRouteRoute: typeof landingRouteRouteWithChildren
  AboutRouteRoute: typeof AboutRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(landing)': {
      id: '/(landing)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof landingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/about/': {
      id: '/about/'
      path: '/'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof AboutRouteRoute
    }
    '/(landing)/': {
      id: '/(landing)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof landingIndexRouteImport
      parentRoute: typeof landingRouteRoute
    }
    '/about/$userId': {
      id: '/about/$userId'
      path: '/$userId'
      fullPath: '/about/$userId'
      preLoaderRoute: typeof AboutUserIdRouteImport
      parentRoute: typeof AboutRouteRoute
    }
    '/about/join-us': {
      id: '/about/join-us'
      path: '/join-us'
      fullPath: '/about/join-us'
      preLoaderRoute: typeof AboutJoinUsRouteRouteImport
      parentRoute: typeof AboutRouteRoute
    }
    '/dashboard/items/': {
      id: '/dashboard/items/'
      path: '/items'
      fullPath: '/dashboard/items'
      preLoaderRoute: typeof DashboardItemsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/about/join-us/': {
      id: '/about/join-us/'
      path: '/'
      fullPath: '/about/join-us/'
      preLoaderRoute: typeof AboutJoinUsIndexRouteImport
      parentRoute: typeof AboutJoinUsRouteRoute
    }
    '/(landing)/contact-us/': {
      id: '/(landing)/contact-us/'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof landingContactUsIndexRouteImport
      parentRoute: typeof landingRouteRoute
    }
    '/dashboard/items/$itemId': {
      id: '/dashboard/items/$itemId'
      path: '/items/$itemId'
      fullPath: '/dashboard/items/$itemId'
      preLoaderRoute: typeof DashboardItemsItemIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface landingRouteRouteChildren {
  landingIndexRoute: typeof landingIndexRoute
  landingContactUsIndexRoute: typeof landingContactUsIndexRoute
}

const landingRouteRouteChildren: landingRouteRouteChildren = {
  landingIndexRoute: landingIndexRoute,
  landingContactUsIndexRoute: landingContactUsIndexRoute,
}

const landingRouteRouteWithChildren = landingRouteRoute._addFileChildren(
  landingRouteRouteChildren,
)

interface AboutJoinUsRouteRouteChildren {
  AboutJoinUsIndexRoute: typeof AboutJoinUsIndexRoute
}

const AboutJoinUsRouteRouteChildren: AboutJoinUsRouteRouteChildren = {
  AboutJoinUsIndexRoute: AboutJoinUsIndexRoute,
}

const AboutJoinUsRouteRouteWithChildren =
  AboutJoinUsRouteRoute._addFileChildren(AboutJoinUsRouteRouteChildren)

interface AboutRouteRouteChildren {
  AboutJoinUsRouteRoute: typeof AboutJoinUsRouteRouteWithChildren
  AboutUserIdRoute: typeof AboutUserIdRoute
  AboutIndexRoute: typeof AboutIndexRoute
}

const AboutRouteRouteChildren: AboutRouteRouteChildren = {
  AboutJoinUsRouteRoute: AboutJoinUsRouteRouteWithChildren,
  AboutUserIdRoute: AboutUserIdRoute,
  AboutIndexRoute: AboutIndexRoute,
}

const AboutRouteRouteWithChildren = AboutRouteRoute._addFileChildren(
  AboutRouteRouteChildren,
)

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardItemsItemIdRoute: typeof DashboardItemsItemIdRoute
  DashboardItemsIndexRoute: typeof DashboardItemsIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardItemsItemIdRoute: DashboardItemsItemIdRoute,
  DashboardItemsIndexRoute: DashboardItemsIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  landingRouteRoute: landingRouteRouteWithChildren,
  AboutRouteRoute: AboutRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
